In [3]:
# NumPy Arrays
import numpy as np

Print type of List

In [4]:
mylist = [1,2,3]
print(type(mylist))

<class 'list'>


Numpy Array

In [5]:

myarray = np.array(mylist)
print(type(myarray))


<class 'numpy.ndarray'>


Numpy 'arange'

In [6]:
arr1 = np.arange(0,10,2)
print(arr1)


[0 2 4 6 8]


Numpy 'Zero' arrays

In [14]:

arr2 = np.zeros(shape=(5,5))
print(arr2)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Numpy 'Ones'

In [12]:
 
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

np 'seed'

In [18]:
np.random.seed(101)
arr = np.random.randint(0,100,10)
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [19]:
arr.max()

95

Get index of maximum value

In [20]:
arr.argmax()

0

In [21]:
arr.reshape(5,2)

array([[95, 11],
       [81, 70],
       [63, 87],
       [75,  9],
       [77, 40]])

Matrix operations

In [24]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [25]:
# Get all rows of the column '1'
mat[:,1]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

Matrix slicing

In [26]:
mat[0:3,0:4]

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [29]:
newmat = mat.copy()
newmat[0:2,0:3] = 999
newmat

array([[999, 999, 999,   3,   4,   5,   6,   7,   8,   9],
       [999, 999, 999,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])